import type { FormConfig, BaseField } from '../types/form';

export const DEFAULT_FORM_TYPES: BaseField[] = [{
  type: 'text',
  id: 'text',
  name: 'text',
  label: 'Text',
  required: false,
  description: 'Single line string input',
  placeholder: 'Enter text...',
}, {
  type: 'number',
  id: 'number',
  name: 'number',
  label: 'Number',
  min: 0,
  max: 120,
  required: false,
  description: 'Numeric input with optional min/max',
  placeholder: 'Enter number...',
},
{
  type: 'textarea',
  id: 'textarea',
  name: 'textarea',
  label: 'Textarea',
  required: false,
  max:500,
  description: "Multi-line string input",
  placeholder: 'Enter textarea...',
}, {
  type: 'checkbox',
  id: 'checkbox',
  name: 'checkbox',
  label: 'Checkbox',
  required: false,
  description: "Multiple option selection",
  placeholder: 'Enter checkbox...',
}, {
  type: 'radio',
  id: 'radio',
  name: 'radio',
  label: 'Radio',
  required: false,
  description: "Single option selection",
  placeholder: 'Enter radio...',
}, {
  type: 'select',
  id: 'select',
  name: 'select',
  label: 'Select',
  required: false,
  description: 'Dropdown with single option selection',
  placeholder: 'Enter select...',
}, {
  type: 'group',
  id: 'group',
  name: 'group',
  label: 'Group',
  description: 'Container for nesting fields recursively',
  required: false,
  fields: [],
}]



export const DEFAULT_FORM_CONFIG: FormConfig = {
  id: 'form_user_registration',
  title: 'User Registration & Profile',
  description: 'A comprehensive onboarding form with personal details and nested contact information.',
  fields: [
    {
      id: 'f_full_name',
      name: 'fullName',
      label: 'Full Name',
      type: 'text',
      required: true,
      placeholder: 'e.g. Jane Doe',
    },
    {
      id: 'f_age',
      name: 'age',
      label: 'Age',
      type: 'number',
      required: true,
      min: 18,
      max: 120,
      placeholder: '18-120',
    },
    {
      id: 'f_contact_group',
      name: 'contactInfo',
      label: 'Contact Information',
      type: 'group',
      required: false,
      fields: [
        {
          id: 'f_email',
          name: 'email',
          label: 'Email Address',
          type: 'text',
          required: true,
          placeholder: 'jane@example.com',
        },
        {
          id: 'f_phone',
          name: 'phoneNumber',
          label: 'Phone Number',
          type: 'text',
          required: false,
          placeholder: '+1 (555) 000-0000',
        },
        {
          id: 'f_address_group',
          name: 'address',
          label: 'Mailing Address (Nested Group)',
          type: 'group',
          required: false,
          fields: [
            {
              id: 'f_street',
              name: 'street',
              label: 'Street Address',
              type: 'text',
              required: true,
              placeholder: '123 Innovation Way',
            },
            {
              id: 'f_postal_code',
              name: 'postalCode',
              label: 'Postal Code',
              type: 'number',
              required: true,
              min: 10000,
              max: 99999,
              placeholder: '90210',
            },
          ],
        },
      ],
    },
  ],
};
